# Generated by Django 3.2.9 on 2021-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skartuser',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
