# Generated by Django 3.2.9 on 2021-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to='skcommeerce.ProductOrder'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='selling_product_category',
            field=models.ManyToManyField(max_length=255, to='skcommeerce.ProductCategory'),
        ),
    ]
