# Generated by Django 3.2.9 on 2021-11-06 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='receiver_mobile_number',
            field=models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
            preserve_default=False,
        ),
    ]
