# Generated by Django 3.2.9 on 2021-11-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0002_placeorder_receiver_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, to='skcommeerce.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_customer', to='skcommeerce.skartuser')),
                ('products', models.ManyToManyField(blank=True, to='skcommeerce.Product')),
            ],
        ),
    ]
