# Generated by Django 3.2.9 on 2021-11-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0003_cancelledorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancelledOrders',
            new_name='CancelledOrder',
        ),
    ]
