# Generated by Django 3.2.9 on 2021-11-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skcommeerce', '0005_auto_20211105_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='user',
            new_name='customer',
        ),
    ]
